# Generated by Django 5.1 on 2024-08-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('ski', 'Ski'), ('botas', 'Botas'), ('trineo', 'Trineo'), ('snowboard', 'Snowboard'), ('otros', 'Otros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('arrendado', 'Arrendado'), ('mantencion', 'Mantencion')], max_length=45),
        ),
    ]
