# Generated by Django 5.1 on 2024-08-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_alter_categoria_nombre_alter_equipo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
