# Generated by Django 5.1 on 2025-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0006_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
