# Generated by Django 6.0.2 on 2026-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0008_alter_arriendo_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='fecha',
            new_name='fecha_arriendo',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
