# Generated by Django 6.0.2 on 2026-02-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0009_rename_fecha_arriendo_fecha_arriendo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_devolucion',
        ),
    ]
